name: Testing 
on: push

jobs: 
  test_project:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Run django unittests
      run: | 
      pip3 install --user django
      cd capstone
      python3 ./manage.py test
